version: "3.7"

services:
  postgres:
    image: postgres:10.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: lpadb
      POSTGRES_USER: lpauser
      POSTGRES_PASSWORD: lpapass

  # ---------------------------
  # Create feedback table and db user for PerfPlat
  feedbackdb:
    container_name: feedbackdb
    image: feedbackdb
    build:
      context: ./
      dockerfile: feedbackdb/docker/app/Dockerfile
    depends_on:
      - postgres
    environment:
      OPG_LPA_STACK_NAME: "local"
      OPG_LPA_STACK_ENVIRONMENT: "dev"
      OPG_LPA_POSTGRES_HOSTNAME: "postgres"
      OPG_LPA_POSTGRES_PORT: "5432"
      OPG_LPA_POSTGRES_NAME: "lpadb"
      OPG_LPA_POSTGRES_USERNAME: "lpauser"
      OPG_LPA_POSTGRES_PASSWORD: "lpapass"
      OPG_LPA_POSTGRES_FEEDBACK_USERNAME: "feedbackuser"
      OPG_LPA_POSTGRES_FEEDBACK_PASSWORD: "feedbackpass"

  rest-api:
    container_name: rest-api
    image: rest-api
    build:
      context: ./
      dockerfile: ./rest-api/docker/app/Dockerfile
    depends_on:
      - postgres
    environment:
      AWS_XRAY_SDK_ENABLED: "false"
      POSTGRES_HOSTNAME: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_NAME: "lpadb"
      POSTGRES_USERNAME: "lpauser"
      POSTGRES_PASSWORD: "lpapass"
    ports:
      - 8005:8005

