name: build-images

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: write
  security-events: none
  statuses: none

jobs:
  build-images:
    name: Build , test and push docker images for feedback apps
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: opg-feedback-ci

      - name: Build and test api and feedbackdb docker images
        run: |
          pip install wait-for-it pytest
          which wait-for-it
          export FEEDBACK_CI=true
          docker-compose build
          # TODO comment for now
          docker-compose up -d
          #wait-for-it -t 30 -s http://0.0.0.0:9004/healthcheck -- echo "healthcheck endpoint reached"
          #wait-for-it -t 30 -s http://0.0.0.0:9004/feedback -- echo "feedback endpoint reached"
          export POSTGRES_NAME=lpadb
          export POSTGRES_USERNAME=lpauser
          export POSTGRES_PASSWORD=lpapass
          cd feedbackapi
          pip install -e .
          # TODO comment for now
          pytest
          docker-compose down
          #TODO temp test - can we talk to secrets mgr within github action using creds we assumed?
          python3 opgfeedbackapi/get_secret.py

      - name: Build and test front docker image
        run: |
          pip install wait-for-it
          which wait-for-it
          docker build -t feedback-front -f front-app/docker/app/Dockerfile .
          docker run -d -p 8005:8005 -e "AWS_XRAY_SDK_ENABLED=false" feedback-front
          # LATER when can run gunicorn , this should work
          #wait-for-it -t 30 -s http://0.0.0.0:8005/healthcheck -- echo "healthcheck endpoint reached"
          docker stop `docker ps | grep feedback-front | awk '{print $NF}'`

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/feedback-actions-ci
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 311462405659

      - name: Extract branch name
        run: |
          if [ "${{ github.head_ref }}" == "" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=${{ github.head_ref }} >> $GITHUB_ENV
          fi
        id: extract_branch
      - uses: unfor19/install-aws-cli-action@v1

      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Push api docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opg-feedback/rest-api
        run: |
          docker tag feedback-rest-api $ECR_REGISTRY/$ECR_REPOSITORY:latest
          if [ $BRANCH_NAME == "main" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ steps.bump_version.outputs.tag }}
          fi
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Push front docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opg-feedback/front-app
        run: |
          docker tag feedback-front $ECR_REGISTRY/$ECR_REPOSITORY:latest
          if [ $BRANCH_NAME == "main" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ steps.bump_version.outputs.tag }}
          fi
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Push feedbackdb docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: opg-feedback/feedbackdb
        run: |
          docker tag feedbackdb $ECR_REGISTRY/$ECR_REPOSITORY:latest
          if [ $BRANCH_NAME == "main" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ steps.bump_version.outputs.tag }}
          fi
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
